# Más información: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.deploy.parameters]
stack_name = "aval-backend"
resolve_s3 = true
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
s3_prefix = "aval-backend"
parameter_overrides = "AppBaseUrl=\"http://localhost:3000\""

[default.global.parameters]
region = "us-east-1"
